  version: '3.9'

  services:
    mysql:
      image: mysql:latest
      container_name: my_sql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mysql_db
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql

    redis:
      image: redis:latest
      container_name: my-redis
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data

    postgres:
      image: postgres:latest
      container_name: postgres_container
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: local
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - mynetwork

    mongodb:
      image: mongo:latest
      container_name: mongodb_container
      ports:
        - "27017:27017"
      networks:
        - mynetwork

  networks:
    mynetwork:
      driver: bridge

  volumes:
    mysql_data:
    redis_data:
    postgres_data: